// 登录
export const LOGIN_ISLOADING = "LOGIN_ISLOADING";
export const LOGIN_OVER = "LOGIN_OVER";
export const LOGIN_ERROR = "LOGIN_ERROR";

// movie
export const LOAD_DISCOVERY_LIST = "LOAD_DISCOVERY_LIST";
export const GET_DISCOVERY_LIST = "GET_DISCOVERY_LIST";
export const RESET_DISCOVERY_LIST = "RESET_DISCOVERY_LIST";